### ISSUE TITLE
Speed controll UX improvement

### ISSUE THREAD

**Issue by piotrKantor** [lidel/yt-looper#164]
- [ ] allowing one letter parameter(s instead of speed) 
- [x] adding speed controll to GUI i.e. = as a 50% increase and -(dash) as 50%(of nominal value) decrease

**Comment by lidel** [comment]
We can't use `&s=` because it is already  taken by the SoundCloud player: 
https://yt.aergia.eu/#s=sacredbones/pharmakon-body-betrays-itself

That being said, second idea is very good: implemented YouTube speed control via <kbd>[</kbd> and <kbd>]</kbd>.
Picked them to avoid undesired volume change via <kbd>-</kbd> and <kbd>+</kbd>, plus these are keys used in [mpv](https://mpv.io/) (for the same purpose).

**Comment by piotrKantor** [comment]
What about 'q' from 'quickness' or 'g' from 'Geschwindigkeit' :D ?
To avoid inconsistency between one letter and whole word the 'speed' could be removed.

**Comment by lidel** [comment]
Ayy, [Wahnsinnige Gschwindigkeit](https://www.youtube.com/watch?v=1mgvE55HpcU)! :turtle:

Jokes aside, I am against complicating things.
Current convention is to follow clarity and simplicity (in that order).

Playlist items have long IDs, are always present, so we use  single tokens:
- `v=`
- `i=`
- `s=`

Global modifiers have full form, are rarely used so should be self-explanatory:
-  `&editor`
- `&random`
- `&quality=`
- `&speed=`

Let's keep it that way.
